import {StyleSheet, Dimensions} from 'react-native';
import R from '../../res/R';

const Styles = StyleSheet.create({

    mainView:
    {
        flex:1, 
        backgroundColor:R.colors.backgroundColor
    },
    firstCardMainView:
    {
        paddingVertical:R.fontSize.Size4 
    },
    firstcardView:
    {
        padding:R.fontSize.padding,
        borderWidth:1, 
        marginHorizontal:R.fontSize.extraSmall, 
        flexDirection:'row', 
        alignItems:'center', 
        justifyContent:'center', 
        borderColor:R.colors.placeholderTextColor, 
        backgroundColor:R.colors.buttonColor,
        shadowColor: "#000",
        shadowOffset: {width: 0,height: 2},
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth:0.4
    },
    symbolLogoMainView:
    {
        alignItems:'center',
        justifyContent:'center', 
        padding:R.fontSize.Size6
    },
    symbolLogoView:
    {
        height:R.fontSize.Size60,
        width:R.fontSize.Size60, 
        borderRadius:R.fontSize.Size40, 
        borderWidth:1, 
        overflow:'hidden', 
        backgroundColor:R.colors.black
    },
    symbolImage:
    {
        height:R.fontSize.Size60,
        width:R.fontSize.Size60, 
        borderRadius:R.fontSize.Size40
    },
    SymbolText:
    {
        fontSize:R.fontSize.medium, 
        fontWeight:'600', 
        color:R.colors.white,
        marginTop:2
    },
    graphView:
    {
        flex:1, 
        marginHorizontal:R.fontSize.Size6
    },
    lineChartStyle:
    {
        height:R.fontSize.Size100,
        marginVertical:R.fontSize.Size4, 
        borderWidth:0.5, 
        borderColor:'#f1f1f1', 
        borderRadius:R.fontSize.Size5
    },
    priceMainView:
    {
        marginRight:R.fontSize.Size4, 
        width:R.fontSize.Size130,
        alignItems:'center'
    },
    priceText:
    {
        fontSize:R.fontSize.large, 
        color:R.colors.black, 
        fontWeight:'700'
    },
    priceRatioView:
    {
        marginVertical:R.fontSize.Size4,
        marginHorizontal:R.fontSize.Size8
    },
    priceRatioText:
    {
        fontSize:R.fontSize.medium, 
        fontWeight:'500',
    },
    aboutMainView:
    {
        marginHorizontal:R.fontSize.extraSmall, 
        borderWidth:1, 
        borderColor:R.colors.placeholderTextColor,
        marginTop:R.fontSize.Size4
    },
    aboutMainTouch:
    {
        padding:R.fontSize.Size5, 
        justifyContent:'center', 
        alignItems:'center',
        backgroundColor:R.colors.buttonColor, 
        borderColor:R.colors.placeholderTextColor, 
        flexDirection:'row'
    },
    aboutDetailView:
    {
        padding:R.fontSize.Size4
    },
    aboutTitleText:
    {
        fontWeight:'500', 
        fontSize:R.fontSize.small, 
        color:R.colors.buttonColor,
        marginTop:2
    },
    aboutValueText:
    {
        color:R.colors.black
    },
    aboutCompanyNameText:
    {
        fontSize:R.fontSize.medium, 
        color:R.colors.buttonColor, 
        fontWeight:'500'
    },
    updownImage:
    {
        height:R.fontSize.XXXLarge, 
        width:R.fontSize.XXXLarge,
    },
    newsMainView:
    {
        flex:1, 
        marginHorizontal:R.fontSize.extraSmall, 
        marginTop:R.fontSize.Size4
    },
    newsArticleText:
    {
        fontSize:R.fontSize.medium, 
        color:R.colors.white, 
        fontWeight:'700',
        flex:1
    },
    updownImageView:
    {
        paddingHorizontal:R.fontSize.Size8
    },
    NewsCardTouch:
    {
        flexDirection:'row',
        marginVertical:R.fontSize.Size4,
        shadowColor: "#000",
        shadowOffset: {width: 0,height: 2},
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        backgroundColor:R.colors.white,
        borderWidth:0.4,
        borderColor:R.colors.placeholderTextColor
    },
    newsImageView:
    {
        height:R.fontSize.Size120,
        width:R.fontSize.Size150, 
        overflow:'hidden', 
        backgroundColor:R.colors.placeholderTextColor
    },
    newsImage:
    {
        height:R.fontSize.Size120, 
        width:R.fontSize.Size150
    },
    PublisherLogoView:
    {
        position:'absolute', 
        height:R.fontSize.Size40,
        width:R.fontSize.Size40, 
        right:R.fontSize.Size4, 
        bottom:R.fontSize.Size4, 
        backgroundColor:R.colors.modelBackground, 
        borderRadius:4, 
        overflow:'hidden'
    },
    PublisherLogo:
    {
        height:R.fontSize.Size40,
        width:R.fontSize.Size40
    },
    publisherText:
    {
        fontSize:R.fontSize.small, 
        color:R.colors.buttonColor, 
        fontWeight:'600',
        marginVertical:1
    },
    publisherTextValue:
    {
        color:R.colors.black, fontWeight:'normal'
    },
    newsTitle:
    {
        fontSize:R.fontSize.medium, 
        fontWeight:'500',
        paddingVertical:2
    },
    ActivityView:
    {
        flex:1, 
        alignItems:'center', 
        justifyContent:'center'
    }
})

export default Styles;